doc/Add breadcrumb info and make general edits
pyansys/pyansys-sphinx-theme pull request #23
Opened 2022-02-03 19:33 UTC by PipKat

2022-02-03 19:35 UTC, PipKat commented
@Andy-Grigg 
I'm sure my poor attempt to add breadcrumb information needs your attention!

2022-02-04 19:27 UTC, Andy-Grigg requested changes
I have suggested some changes to the breadcrumb explanation. The other changes in this PR all make sense.

2022-02-04 19:27 UTC, Andy-Grigg commented on doc/source/usage.rst
> +breadcrumbs to the pages of your documentation, in the ``theme.conf``
```suggestion
breadcrumbs to the pages of your documentation, in the ``conf.py``
```

2022-02-04 19:27 UTC, Andy-Grigg commented on doc/source/usage.rst
> +file, set ``html_theme_option`` to ``"show_breadcrumbs": True``.
```suggestion
file, add ``"show_breadcrumbs": True`` to the ``html_theme_options`` dictionary.
```

2022-02-04 19:27 UTC, Andy-Grigg commented on doc/source/usage.rst
> +PyAnsys root page, you set ``html_theme_option`` to
```suggestion
PyAnsys Documentation homepage, add them to the ``html_theme_options`` dictionary as a list of tuples
```

2022-02-04 19:27 UTC, Andy-Grigg commented on doc/source/usage.rst
> +``"additional_breadcrumbs": [("Link text", "href")]``.
```suggestion
with the ``"additional_breadcrumbs"`` key. The tuples are of the form ``("Link text", "url")``.
```

2022-02-04 19:27 UTC, Andy-Grigg commented on doc/source/usage.rst
> +You must manually add the breadcrumb that links to the module homepage when on
```suggestion
When on the module homepage, a breadcrumb will be displayed with the homepage title.
```

2022-02-04 19:27 UTC, Andy-Grigg commented on doc/source/usage.rst
> +a page within the documentation. Because there is no way to get the title of the
```suggestion
However, this title is not accessible to Sphinx from other documentation pages. Therefore, the ``html_short_title``
```

2022-02-04 19:27 UTC, Andy-Grigg commented on doc/source/usage.rst
> +``index.rst`` page, you must use the ``html_title`` set in the ``conf.py``
```suggestion
is used as the display text for the documentation homepage breadcrumb. To ensure a consistent user experience
```

2022-02-04 19:27 UTC, Andy-Grigg commented on doc/source/usage.rst
> +file. The problem is that this isn't necessarily the same as the title of the
```suggestion
you should ensure the ``html_short_title`` (or optionally ``html_title`` if ``html_short_title`` is not used)
```

2022-02-04 19:27 UTC, Andy-Grigg commented on doc/source/usage.rst
> +``index.rst`` page.
```suggestion
is set to the same value as the title of the ``index.rst`` page. If you want to use the version number
in the ``index.rst`` title, use ``|version|`` to include the package version number. 
```

2022-02-04 19:27 UTC, Andy-Grigg commented on doc/source/usage.rst
> +the body of documentation pages to make navigation easier. To add
```suggestion
the body of documentation pages to make navigation easier. These 
breadcrumbs are disabled by default. To add
```

2022-02-08 15:29 UTC, akaszynski approved these changes
This looks good to me. Thanks for adding it!

2022-02-08 15:30 UTC, merged